/* Create an AWS key pair, store the private key in a pem file in the directory 
#    that the tf script is run from. 
#    Generating a 4 digit random string to append to file name to distinguish 
#    between multiple runs of the script. [key name format e.g. terraform-key-pair.1729 (and .pem on file)]
#      --  Dan Edeen, dan@dsblue.net, 2022  --
*/

resource "random_id" "getrandom" {
  keepers = {
    first = "$timestamp()}"
  }
  byte_length = 2
}

## Define your key variable
variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}

locals {
  keypair_name = "${var.generated_key_name}.${random_id.getrandom.hex}"
}

 
## Generate SSH key content using terraform
resource "tls_private_key" "dev_key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}
 
## Create a AWS key pair using the ssh key generated previously
resource "aws_key_pair" "generated_key" {
  key_name   = local.keypair_name
  public_key = tls_private_key.dev_key.public_key_openssh
  tags = {
    Owner = "dan-via-terraform"
  }
 
  provisioner "local-exec" {    # Generate key-pair.pem" in current directory
    command = <<-EOT
      echo '${tls_private_key.dev_key.private_key_pem}' > ./'${local.keypair_name}'.pem
      #chmod 400 ./'${var.generated_key_name}'.pem
      chmod 400 ./'${local.keypair_name}'.pem
    EOT
  }
 
}
